// Vitest globalSetup: `teardown` runs once, in the main process, after the whole run.
//
// server/test/helpers.js drops each test's schema in its own afterAll, but that only
// fires when the file finishes cleanly — a crashed worker or a killed run leaks `tp_%`
// schemas into the shared tripper_test database, where they accumulate without bound
// (4121 of them had piled up by the time this was added). Same belt-and-braces cleanup
// e2e/smoke.mjs already does for its own tp_smoke_* schema — excluded from this sweep
// (below) so a smoke run overlapping a vitest run doesn't get its schema dropped
// mid-flight. helpers.js names vitest schemas `tp_<pid>_<n>` (pid is numeric), which
// can never match `tp_smoke_%`.
import { makeDb } from '../src/db.js'
import { TEST_URL } from './test-db-url.js'

export async function setup() { /* nothing to do before the run */ }

export async function teardown() {
  const db = await makeDb({ url: TEST_URL, driver: 'pg' })
  try {
    const rows = await db.all(
      `SELECT nspname FROM pg_namespace WHERE nspname LIKE 'tp\\_%' AND nspname NOT LIKE 'tp\\_smoke\\_%'`
    )
    for (const { nspname } of rows) {
      // Identifiers cannot be parameterised. These names are generated by this repo's own
      // fixtures and matched against a fixed prefix, never user input.
      await db.exec(`DROP SCHEMA IF EXISTS "${nspname}" CASCADE`)
    }
    if (rows.length) console.log(`globalTeardown: dropped ${rows.length} leftover tp_% schema(s)`)
  } finally {
    await db.close()
  }
}
